objective:
  name: AWR
  alpha: 0.5
  beta: 10

model:
  model_kwargs:
    value_head_config:
      is_detached: false

training:
  effective_batch_size: 512
  learning_rate: 0.001
  save_steps: 3346

generation:
  every_n_steps: 32

kl_gpt3_callback:
  every_n_steps: 32
